language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
script:
  - yarn global add serverless
  - yarn deploy -v --stage prod > output.txt
  - "ENDPOINT=$(grep 'ServiceEndpoint:' output.txt | sed 's/^.*: //')"
  - echo $ENDPOINT
  - curl -S https://api.telegram.org/bot$BOT_TOKEN/setWebhook?url=$ENDPOINT/send
  - echo success!
