service: telegram-form-bot-serverless

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1
  logRetentionInDays: 3
  environment:
    TO: ${file(./env.json):TO, env:TO}
    FROM: ${file(./env.json):FROM, env:FROM},
    LANG: ${file(./env.json):LANG, env:LANG}
    BOT_TOKEN: ${file(./env.json):BOT_TOKEN, env:BOT_TOKEN}
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    BUCKET: ${file(./env.json):BUCKET_NAME, env:BUCKET_NAME}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:*"
      Resource:
        - "*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:provider.environment.BUCKET}/*"

custom:
  s3Bucket: formbucket-${self:provider.environment.BUCKET}

functions:
  send:
    handler: handler.sendAnswer
    events:
      - http:
          path: send
          method: post

resources:
  Resources:
    AnswersDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE}

package:
  exclude:
    - src/tests/**
    - jest.config.js
    - tsconfig.json
    - tslint.json
    - env*.json
    - .travis.yml
    - .prettierrc
    - node_modules/aws-sdk/**
